# T3 Foundation Gemstone Project [t3gemstone.org]
# SPDX-License-Identifier: Apache-2.0

version: "3"

vars:
  TOOLS_PATH: '{{ .TOOLS_PATH | default "tisdk" }}'
  MCU_PLUS_SDK_PATH: '{{ .MCU_PLUS_SDK_PATH | default "tisdk/ti-processor-sdk-rtos-j722s-evm-10_01_00_04/mcu_plus_sdk_j722s_10_01_00_22" }}'
  CGT_TI_ARM_CLANG_PATH: '{{ .CGT_TI_ARM_CLANG_PATH | default "tisdk/ti-cgt-armllvm_3.2.2.LTS" }}'

env:
  TOOLS_PATH: "{{ .TOOLS_PATH }}"
  MCU_PLUS_SDK_PATH: "{{ .MCU_PLUS_SDK_PATH }}"
  CGT_TI_ARM_CLANG_PATH: "{{ .CGT_TI_ARM_CLANG_PATH }}"

tasks:
  default:
    silent: true
    cmds:
      - task --list-all --summary

  build: make all

  clean: make clean

  scrub: make scrub
  
  syscfg-gui: make syscfg-gui

  syscfg: make syscfg

  generate-compile-commands: bear --config semantics_cfg.json -- make -C {{.TASKFILE_DIR}} -B

  install-deps:
    cmds:
      - sudo apt install -y curl libtinfo5

  install-sdk:
    vars:
      TARGET_DIR: '{{ .TARGET_DIR | default "tisdk" }}'
      sdk_link: "https://dr-download.ti.com/software-development/software-development-kit-sdk/MD-1bSfTnVt5d/10.01.00.04/ti-processor-sdk-rtos-j722s-evm-10_01_00_04.tar.gz"
      tiarmclang_link: "https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-ayxs93eZNN/3.2.2.LTS/ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin"
      syscfg_link: https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-nsUM6f7Vvb/1.20.0.3587/sysconfig-1.20.0_3587-setup.run
      gcc_aarch64_link: https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz
      gcc_none_link: https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz
      c7000_link: https://dr-download.ti.com/software-development/ide-configuration-compiler-or-debugger/MD-707zYe3Rik/4.1.0.LTS/ti_cgt_c7000_4.1.0.LTS_linux-x64_installer.bin

    cmds:
      - task: install-deps
      - mkdir -p downloads/ {{.TARGET_DIR}}/
      - curl -C - -L -# -o downloads/sysconfig-1.20.0_3587-setup.run {{.syscfg_link}}
      - curl -C - -L -# -o downloads/ti-processor-sdk-rtos-j722s-evm-10_01_00_04.tar.gz {{.sdk_link}}
      - curl -C - -L -# -o downloads/ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin {{.tiarmclang_link}}
      - curl -C - -L -# -o downloads/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz {{.gcc_aarch64_link}}
      - curl -C - -L -# -o downloads/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz {{.gcc_none_link}}
      - curl -C - -L -# -o downloads/ti_cgt_c7000_4.1.0.LTS_linux-x64_installer.bin {{.c7000_link}}
      - tar -xzvf downloads/ti-processor-sdk-rtos-j722s-evm-10_01_00_04.tar.gz -C {{.TARGET_DIR}}/
      - tar -xJvf downloads/gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf.tar.xz -C {{.TARGET_DIR}}/
      - tar -xJvf downloads/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz -C {{.TARGET_DIR}}/
      - chmod u+x downloads/ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin 
      - chmod u+x downloads/sysconfig-1.20.0_3587-setup.run
      - chmod u+x downloads/ti_cgt_c7000_4.1.0.LTS_linux-x64_installer.bin
      - ./downloads/ti_cgt_armllvm_3.2.2.LTS_linux-x64_installer.bin --prefix "{{.TARGET_DIR}}/" --unattendedmodeui minimal --mode unattended
      - ./downloads/sysconfig-1.20.0_3587-setup.run --prefix "{{.TARGET_DIR}}/sysconfig_1.20.0/" --unattendedmodeui minimal --mode unattended
      - ./downloads/ti_cgt_c7000_4.1.0.LTS_linux-x64_installer.bin --prefix "{{.TARGET_DIR}}/" --unattendedmodeui minimal --mode unattended
