name: Build texas-am67-sbl-gemboot

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install taskfile for build project
        run: |
            mkdir "${GITHUB_WORKSPACE}/bin"
            sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b "${GITHUB_WORKSPACE}/bin"

      - name: Install SDK
        run: |
            "${GITHUB_WORKSPACE}/bin/task" install-sdk
      
      - name: Build project
        run: |
            "${GITHUB_WORKSPACE}/bin/task" build
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gemimager-tiboot3-t3-gem-o1
          path: ${{ github.workspace }}/build/tiboot3.bin
